default_context:
  project_name: 'L2 IoT Dashboard'
  project_slug: 'thdash'
  domain_main: 'toplinker.top'
  domain_staging: 'stag.toplinker.top'
  docker_swarm_stack_name_main: 'toplinker-top'
  docker_swarm_stack_name_staging: 'stag-toplinker-top'
  secret_key: '42832e6ae3ef6a5950ff5ec67e6ddaab9c30e91c99f38719a2450ae9e78f0e83'
  first_superuser: 'admin'
  first_superuser_password: 'admin'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.toplinker.top", "https://stag.toplinker.top", "https://toplinker.top", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '465'
  smtp_host: 'smtp.163.com'
  smtp_user: 'toplinker_public@163.com'
  smtp_password: 'WTGBUJTQJVDHWWUN'
  smtp_emails_from_email: 'toplinker_public@163.com'
  postgres_password: 'TopLinker0510'
  pgadmin_default_user: 'admin'
  pgadmin_default_user_password: 'admin'
  traefik_constraint_tag: 'toplinker.top'
  traefik_constraint_tag_staging: 'stag.toplinker.top'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:admin'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
